name: Format
on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  format:
    runs-on: ubuntu-latest
    name: Format Files
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: upgrade yarn
        run: yarn set version berry

      - name: install dependencies
        run: yarn install --frozen-lockfile

      - name: run format
        run: yarn run format
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        id: format-files
        with:
          commit_message: "style: format files"
          skip_checkout: true
          branch: "style/formatting"
          create_branch: true

      # create PR using GitHub CLI if files were formatted
      - name: create PR with formatted files
        if: steps.format-files.outputs.changes_detected == 'true'
        id: create-pr
        run: git checkout style/formatting && gh pr create --base main --head style/formatting --title 'Merge formatting into main' --body 'Created by Github action'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # merge PR using GitHub CLI
      - name: merge PR with adjusted formatting
        if: steps.format-files.outputs.changes_detected == 'true'
        id: merge-pr
        run: gh pr merge --admin --merge --subject 'Merge formatting' --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
